# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Serhii Yalosovetskyi
title: Python Developer
email: serg.yalosovetsky@gmail.com
phone: +380(95)224-00-16
website: https://serg-yalosovetsky.github.io/CV/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  serg_yalosovetsky
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
telegram_username: syalosovetskyi
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: serhii-yalosovetskyi
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: telegram
  icon: fab fa-telegram 
  url: https://t.me/syalosovetskyi
# - title: another link
#   icon: fab fa-telegram (https://fontawesome.com/icons/telegram?s=brands)
#   url: https://t.me/syalosovetskyi

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1559807208393.jpg
about_content: | # this will include new lines to allow paragraphs
  Besides experience in software development, I also have experience in cybersecurity and Linux administration. I strive to broaden my horizons, I am glad to have the opportunity to develop in related fields. The priority schedule is full-time or remote work. Development experience is 2 year.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
       # quote: >
       #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          -	Python 3, fastapi, asyncio, pytest, ORM skills (sqlalchemy) and <mark>django</mark>;
          -	Experience with SQL, Redis, PostgreSQL;
          -	Experience in Ansible, AWS, Kubernetes, <mark>Docker</mark> and Terraform
          -	Intermediate English;
          -	HTML, CSS: at the level of creating simple pages, native Javascript (ES6 standard);
          -	Experience with VCS Git and gh;
          -	Extensive experience in using <mark>Linux</mark> OS, in particular - Ubuntu and Kali Linux;
          -	I have an understanding and basic skills in android development;
          -	I have knowledge and skills in <mark>cybersecurity</mark>, good at cryptography;
          - Experience in web and mobile pentesting with Burpsuite, Wireshark and Metasploit
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Zeus Electronics
        link: https://zeuselectronics.eu/
        # link_text: boringcompany.com
        sub_title: Python Developer 
        caption: October 2021 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            -	Participated in defining business requirements for many projects
            -	Development and deployment of Fyuzd application – audio streaming service with full audio stream synchronization;
            -	Support and development of Allgram application – secure chat;
            -	Website and REST API testing;
            
      - layout: left
        title: Vodafone Ukraine
        link: https://www.vodafone.ua/
        # link_text: boringcompany.com
        sub_title: Cybersecurity Specialist 
        caption: October 2018 - March 2021
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          -	Participated in defining business requirements for many projects
          -	Development of REST application services for security testing multiple APIs;
          -	Participated in the development of Vodafone's internal security standards based on international security standards ISO 27001 and OWASP Application Security Verification Standard
          -	Maintained and improved IT infrastructure security with McAfee Endpoint Security and VMware ONE UEM, have experience in networking
          -	Website and mobile application security testing, first of all – My Vodafone. For pentesting used apktool, MobSF, Nessus, Qualys, sqlmap, Burpsuite, OWASP ZAP, sqlmap, Wireshark,   
          -	Scripting in VBA and bash to automate the routine


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NTUU KPI
        caption: 2014 - 2018
        sub_title: Bachelor, Systems Engineering, Faculty of Informatics and Computer Engineering

  - title: Pet projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: [CAPTCHA](https://github.com/serg-yalosovetsky/captcha)
        caption: Services for generating CAPTCHA 
        description: |
          
           - Use Russian or English text, with random peek two or three sequence words
           - Random background color, random color of letters, with good readability
           - Radial gradient for additional complexity of automatic recognition
           - Random font type and size
           - Random font tilt
# [CAPTCHA](https://github.com/serg-yalosovetsky/captcha)

#  - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
      
#   - title: Pet projects
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Services for generating CAPTCHA (https://github.com/serg-yalosovetsky/captcha)
#      - Use Russian or English text, with random peek two or three sequence words
#      - Random background color, random color of letters, with good readability
#      - Radial gradient for additional complexity of automatic recognition
#      - Random font type and size
#      - Random font tilt

#     Look at this cool image  
 #    ![Example](https://github.com/serg-yalosovetsky/captcha/blob/main/captcha.png "Example")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
