title: Serhii Yalosovetskyi  # Add a space after the period

logo: 1.jpg # Use a relative path to logo image 

description: Full Stack Software Engineer - crafting seamless digital experiences where code meets creativity. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "Ek0viIJr71-HdkqLU5XvcMRTtE4x655Xd2K4QJkMywg" # Verify ownership through Search Console  

email: serg.yalosovetsky@gmail.com # Allow visitors to contact you
